# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dialogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='greeting',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='if_neg',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='if_pos',
            field=models.CharField(max_length=500),
        ),
    ]
